// ==UserScript==
// @name         WheelOfNamesTimer
// @namespace    http://rix0r.nl/
// @version      0.0.1
// @description  Wheel Of Names
// @author       Rico
// @require      http://code.jquery.com/jquery-latest.js
// @match        https://wheelofnames.com/*
// ==/UserScript==

$(function() {
  const SECONDS = 100;

  let timer: TimerHandler | undefined;
  let startTime: number = 0;

  $(document).on('click', 'button:contains("Remove")', function() {
    startTimer();
  });

  function startTimer() {
    $('#timer').remove();
    $(`<div id="timer">${SECONDS}</div>`).appendTo($('.q-page-container'));
    startTime = Date.now();
    updateDisplay();
  }

  function updateDisplay() {
    const secondsElapsed = Math.floor((Date.now() - startTime) / 1000);
    const secondsRemaining = Math.max(SECONDS - secondsElapsed, 0);
    $('#timer').text(`${secondsRemaining}`);
    $('#timer').toggleClass('chopchop', 10 < secondsRemaining && secondsRemaining <= 30);
    $('#timer').toggleClass('hurry', secondsRemaining <= 10);
    if (secondsRemaining > 0) {
      setInterval(updateDisplay, 1000);
    } else {
      $('#timer').addClass('jello-horizontal');
    }
  }

      //--- Style our newly added elements using CSS.
  GM_addStyle(`
    #timer {
      position: absolute;
      top: 10px;
      right: 60px;
      width: 2em;
      text-align: center;
      font-size: 20vh;
      font-weight: bold;
    }

    .chopchop {
      color: orange;
    }

    .hurry {
      color: red;
    }

    /* https://animista.net/  */
    .jello-horizontal {
      -webkit-animation: jello-horizontal 0.9s both;
              animation: jello-horizontal 0.9s both;
      animation-iteration-count: infinite;
    }

    /* ----------------------------------------------
    * Generated by Animista on 2024-4-10 17:55:50
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info.
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

   /**
    * ----------------------------------------
    * animation jello-horizontal
    * ----------------------------------------
    */
   @-webkit-keyframes jello-horizontal {
     0% {
       -webkit-transform: scale3d(1, 1, 1);
               transform: scale3d(1, 1, 1);
     }
     30% {
       -webkit-transform: scale3d(1.25, 0.75, 1);
               transform: scale3d(1.25, 0.75, 1);
     }
     40% {
       -webkit-transform: scale3d(0.75, 1.25, 1);
               transform: scale3d(0.75, 1.25, 1);
     }
     50% {
       -webkit-transform: scale3d(1.15, 0.85, 1);
               transform: scale3d(1.15, 0.85, 1);
     }
     65% {
       -webkit-transform: scale3d(0.95, 1.05, 1);
               transform: scale3d(0.95, 1.05, 1);
     }
     75% {
       -webkit-transform: scale3d(1.05, 0.95, 1);
               transform: scale3d(1.05, 0.95, 1);
     }
     100% {
       -webkit-transform: scale3d(1, 1, 1);
               transform: scale3d(1, 1, 1);
     }
   }
   @keyframes jello-horizontal {
     0% {
       -webkit-transform: scale3d(1, 1, 1);
               transform: scale3d(1, 1, 1);
     }
     30% {
       -webkit-transform: scale3d(1.25, 0.75, 1);
               transform: scale3d(1.25, 0.75, 1);
     }
     40% {
       -webkit-transform: scale3d(0.75, 1.25, 1);
               transform: scale3d(0.75, 1.25, 1);
     }
     50% {
       -webkit-transform: scale3d(1.15, 0.85, 1);
               transform: scale3d(1.15, 0.85, 1);
     }
     65% {
       -webkit-transform: scale3d(0.95, 1.05, 1);
               transform: scale3d(0.95, 1.05, 1);
     }
     75% {
       -webkit-transform: scale3d(1.05, 0.95, 1);
               transform: scale3d(1.05, 0.95, 1);
     }
     100% {
       -webkit-transform: scale3d(1, 1, 1);
               transform: scale3d(1, 1, 1);
     }
   }

  `);

  /**
   * Polyfill for old GM_addStyle (still exists in TamperMonkey but
   * got removed in GreaseMonkey 4).
   */
  function GM_addStyle(aCss: string) {
    let head = document.getElementsByTagName('head')[0];
    if (!head) { return null; }
    let style = document.createElement('style');
    style.setAttribute('type', 'text/css');
    style.textContent = aCss;
    head.appendChild(style);
    return style;
  }
});